/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: dylanheyes (https://sketchfab.com/dylanheyes)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modern-kitchen-9843a830b96142a9a53f45f25304d93c
Title: Modern Kitchen
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[599.392, 190.633, 63.681]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[5.354, 4.819, 8.923]}>
          <mesh geometry={nodes.Hob_Material_0.geometry} material={materials.Material} />
          <mesh geometry={nodes.Hob_Hob_0.geometry} material={materials.material} />
        </group>
        <group position={[658.811, 205.109, -71.041]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={17.111}>
          <mesh geometry={nodes.SmallPlant_Bark_0.geometry} material={materials.Bark} />
          <mesh geometry={nodes.SmallPlant_Pot_0.geometry} material={materials.material_16} />
          <mesh geometry={nodes.SmallPlant_Plant_0.geometry} material={materials.Plant} />
        </group>
        <group position={[491.452, 317.41, -361.269]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[113.73, 90, 1331.953]}>
          <mesh geometry={nodes.Ovens_Handles_0.geometry} material={materials.Handles} />
          <mesh geometry={nodes.Ovens_Oven_0.geometry} material={materials.Oven} />
          <mesh geometry={nodes.Ovens_Hob_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Ovens_OvenWindow_0.geometry} material={materials.OvenWindow} />
          <mesh geometry={nodes.Ovens_OvenClock_0.geometry} material={materials.OvenClock} />
        </group>
        <group position={[-51.067, 80.144, 119.451]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[100, 370, 980]}>
          <mesh geometry={nodes.Fridge_FridgeInside_0.geometry} material={materials.FridgeInside} />
          <mesh geometry={nodes.Fridge_FridgeGlass_0.geometry} material={materials.FridgeGlass} />
          <mesh geometry={nodes.Fridge_Counter_0.geometry} material={materials.material_0} />
        </group>
        <mesh geometry={nodes.Structure_Wall_0.geometry} material={materials.Wall} position={[85.764, -27.155, 29.602]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[514.8, 475.2, 8.712]} />
        <mesh geometry={nodes.Floor_Wall_0.geometry} material={materials.Wall} position={[85.764, -27.155, 29.602]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[514.8, 475.2, 8.712]} />
        <mesh geometry={nodes.Window_Window_0.geometry} material={materials.Window} position={[85.764, -27.155, 29.602]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[514.8, 475.2, 8.712]} />
        <mesh geometry={nodes.WindowTrim_CupboardTrim_0.geometry} material={materials.CupboardTrim} position={[85.764, -27.155, 29.602]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[514.8, 475.2, 8.712]} />
        <mesh geometry={nodes.Ceiling_Ceiling_0.geometry} material={materials.Ceiling} position={[85.764, -27.155, 29.602]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[514.8, 475.2, 8.712]} />
        <mesh geometry={nodes.Stairs_Stairs_0.geometry} material={materials.Stairs} position={[724.871, -2.231, 611.403]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[514.8, 475.2, 8.712]} />
        <mesh geometry={nodes.Counters_Counter_0.geometry} material={materials.material_0} position={[599.392, 183.95, 167.541]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
        <mesh geometry={nodes.Tiles_Tiles_0.geometry} material={materials.Tiles} position={[85.764, -27.155, 29.602]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[514.8, 475.2, 8.712]} />
        <mesh geometry={nodes.Cupboards_Cupboard_0.geometry} material={materials.Cupboard} position={[-51.067, 80.144, 119.451]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[100, 370, 980]} />
        <mesh geometry={nodes.Stools_Chair_0.geometry} material={materials.Chair} position={[-164.325, 131.012, 119.451]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[40, 40, 3.36]} />
        <mesh geometry={nodes.LightSupport_Chrome_0.geometry} material={materials.Chrome} position={[0, 491.905, 119.451]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[6.447, 7, 10]} />
        <mesh geometry={nodes.LightsGlass_LightGlass_0.geometry} material={materials.LightGlass} position={[0, 404.128, 119.451]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[6.447, 7, 10]} />
        <mesh geometry={nodes.Lightbulbs_Lights_0.geometry} material={materials.Lights} position={[0, 430.618, -80.549]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[5.158, 5.6, 8]} />
        <mesh geometry={nodes.Trim_CupboardTrim_0.geometry} material={materials.CupboardTrim} position={[-51.067, 80.144, 119.451]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[100, 370, 980]} />
        <mesh geometry={nodes.Sink_Sink_0.geometry} material={materials.Sink} position={[635.665, 198.4, 298.595]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[4.118, 4.118, 6.864]} />
        <mesh geometry={nodes.WindowWall_Wall_0.geometry} material={materials.Wall} position={[85.764, -27.155, 29.602]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[514.8, 475.2, 8.712]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
