/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: QuarizonStudio (https://sketchfab.com/QuarizonStudio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modern-scandinavian-kitchen-island-a9738f4e651b4779acdddcfbb89516f6
Title: modern scandinavian kitchen island
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/kitchen_2.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 149.403, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[410.796, 352.988, 150]}>
          <mesh geometry={nodes.house_house2_0.geometry} material={materials.house2} />
          <mesh geometry={nodes.house_house1_0.geometry} material={materials.house1} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.oven_oven1_0.geometry} material={materials.oven1} />
          <mesh geometry={nodes.oven_oven2_0.geometry} material={materials.oven2} />
          <mesh geometry={nodes.oven_oven3_0.geometry} material={materials.oven3} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.bar_bar1_0.geometry} material={materials.bar1} />
          <mesh geometry={nodes.bar_bar2_0.geometry} material={materials.bar2} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.vase_dec_vase_dec1_0.geometry} material={materials.vase_dec1} />
          <mesh geometry={nodes.vase_dec_vase_cup2_0.geometry} material={materials.vase_cup2} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.book_book1_0.geometry} material={materials.book1} />
          <mesh geometry={nodes.book_book2_0.geometry} material={materials.book2} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.light_light1_0.geometry} material={materials.light1} />
          <mesh geometry={nodes.light_light2_0.geometry} material={materials.light2} />
          <mesh geometry={nodes.light_light3_0.geometry} material={materials.light3} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.seat_seat1_0.geometry} material={materials.seat1} />
          <mesh geometry={nodes.seat_seat2_0.geometry} material={materials.seat2} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.curtain_curtain1_0.geometry} material={materials.curtain1} />
          <mesh geometry={nodes.curtain_curtain2_0.geometry} material={materials.curtain2} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.dec_dec1_0.geometry} material={materials.dec1} />
          <mesh geometry={nodes.dec_dec2_0.geometry} material={materials.dec2} />
          <mesh geometry={nodes.dec_dec3_0.geometry} material={materials.dec3} />
          <mesh geometry={nodes.dec_dec4_0.geometry} material={materials.dec4} />
        </group>
        <mesh geometry={nodes.wood_wood_0.geometry} material={materials.wood} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.table_table_0.geometry} material={materials.table} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.frame_frame_0.geometry} material={materials.frame} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.carpet_carpet_0.geometry} material={materials.carpet} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.cup_cup_0.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.vase_vase_0.geometry} material={materials.vase} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.cooking_bench_cooking_bench_0.geometry} material={materials.cooking_bench} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.tree_tree_0.geometry} material={materials.tree} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.leaves001_leaves_0.geometry} material={materials.leaves} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/kitchen_2.gltf')
