/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 patio_2.gltf 
Author: G&L Architectural Graphics Inc (https://sketchfab.com/BERSEKAEL)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rear-covered-patio-100121-a-2603f0f33747470c90959defe94b7247
Title: Rear Covered Patio 100121 A
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/patio_2.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <mesh geometry={nodes.Material2.geometry} material={materials.material} />
        <mesh geometry={nodes.Material2_1.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Material2_2.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Material2_3.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Material2_4.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Material2_5.geometry} material={materials.material_4} />
        <mesh geometry={nodes.Material2_6.geometry} material={materials.material_5} />
        <mesh geometry={nodes.Material2_7.geometry} material={materials.material_6} />
        <mesh geometry={nodes.Material2_8.geometry} material={materials.material_7} />
        <mesh geometry={nodes.Material2_9.geometry} material={materials.material_8} />
        <mesh geometry={nodes.Material2_10.geometry} material={materials.material_9} />
        <mesh geometry={nodes.Material2_11.geometry} material={materials.material_10} />
        <mesh geometry={nodes.Material2_12.geometry} material={materials.material_11} />
        <mesh geometry={nodes.Material2_13.geometry} material={materials.material_12} />
        <mesh geometry={nodes.Material2_14.geometry} material={materials.material_13} />
        <mesh geometry={nodes.Material2_15.geometry} material={materials.material_14} />
        <mesh geometry={nodes.Material2_16.geometry} material={materials.material_15} />
        <mesh geometry={nodes.Material2_17.geometry} material={materials.material_16} />
        <mesh geometry={nodes.Material2_18.geometry} material={materials.material_17} />
        <mesh geometry={nodes.Material2_19.geometry} material={materials.material_18} />
        <mesh geometry={nodes.Material3.geometry} material={materials.material_19} />
        <mesh geometry={nodes.Material3_1.geometry} material={materials.material_20} />
        <lineSegments geometry={nodes.Material2_20.geometry} material={materials.edge_color000255} />
        <mesh geometry={nodes.Material2_21.geometry} material={materials.material_21} />
        <mesh geometry={nodes.Material2_22.geometry} material={materials.material_22} />
        <mesh geometry={nodes.Material2_23.geometry} material={materials.material_23} />
        <mesh geometry={nodes.Material3_2.geometry} material={materials.material_24} />
        <mesh geometry={nodes.Material2_24.geometry} material={materials.material_25} />
        <mesh geometry={nodes.Material2_25.geometry} material={materials.material_26} />
        <mesh geometry={nodes.Material2_26.geometry} material={materials.material_27} />
      </group>
    </group>
  )
}

useGLTF.preload('/patio_2.gltf')
