/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: gozdemrl (https://sketchfab.com/gozdemrl)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kitchen-interior-design-1021cb0ce71949efaa7240d6fb9f3899
Title: Kitchen Interior Design
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  useGLTF.preload('/3DModels/KitchenModels/kitchen.gltf');
  const { nodes, materials } = useGLTF('/3DModels/KitchenModels/kitchen.gltf'); 
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[25.396, 213.8, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.defaultMaterial_16.geometry} material={materials.Window} />
            <mesh geometry={nodes.defaultMaterial_17.geometry} material={materials.window_Glass} />
          </group>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Tree} position={[-162.527, 21.456, 769.101]} rotation={[-Math.PI / 2, 0, -1.146]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Vazo} position={[-162.134, 20.68, 766.988]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.Other_Object} position={[-247.369, 166.804, 58.929]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.Other_Object} position={[207.325, 134.601, 268.244]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.Other_Object} position={[-259.081, 347.719, -40.226]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.Other_Object} position={[194.311, 136.929, -203.774]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.Other_Object} position={[-259.179, 81.209, 255.144]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.Other_Object} position={[-241.542, 272.356, -35.235]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_8.geometry} material={materials.Other_Object} position={[-241.542, 272.356, 310.524]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_9.geometry} material={materials.Other_Object} position={[-206.114, 92.606, 144.084]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_10.geometry} material={materials.Other_Object} position={[110.88, 23.819, 195.306]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_11.geometry} material={materials.Lights} position={[523.416, 481.732, 672.76]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_12.geometry} material={materials.Lights} position={[134.121, 358.316, 141.921]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_13.geometry} material={materials.Lights} position={[134.121, 501.337, 265.446]} rotation={[-Math.PI / 2, 0, 0]} scale={[5.336, 145.586, 9.82]} />
          <mesh geometry={nodes.defaultMaterial_14.geometry} material={materials.Lights} position={[134.121, 452.138, 265.446]} rotation={[-Math.PI / 2, 0, 0]} scale={[10.329, 166.713, 9.82]} />
          <mesh geometry={nodes.defaultMaterial_15.geometry} material={materials.Window} position={[-250.486, 354.134, 145.624]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_18.geometry} material={materials.Window} position={[-289.13, 238.499, 150.761]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_19.geometry} material={materials.Base_Build} position={[600.577, 282.177, 43.149]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_20.geometry} material={materials.Base_Build} position={[777.493, 229.722, 288.066]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_21.geometry} material={materials.Base_Build} position={[-274.976, 215.63, 208.385]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_22.geometry} material={materials.Base_Build} position={[284.635, 269.358, -274.753]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_23.geometry} material={materials.Base_Build} position={[205.196, 622.013, 289.117]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_24.geometry} material={materials.Base_Build} position={[267.23, -24.569, 289.128]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_25.geometry} material={materials.Base_Build} position={[611.63, 634.253, 289.675]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_26.geometry} material={materials.material} position={[-216.128, 194.534, 457.936]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_27.geometry} material={materials.Cabinet_glass} position={[571.201, 92.711, 421.276]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_28.geometry} material={materials.Big_Cabinet} position={[566.275, 92.711, 421.276]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_29.geometry} material={materials.Big_Cabinet} position={[546.856, 493.442, 256.925]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_30.geometry} material={materials.Big_Cabinet} position={[546.856, 493.442, 97.541]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_31.geometry} material={materials.Big_Cabinet} position={[-259.179, 81.209, 414.687]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_32.geometry} material={materials.Freezer} position={[522.436, 192.425, 388.067]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_33.geometry} material={materials.Chair} position={[277.935, 32.96, 143.591]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_34.geometry} material={materials.Chair} position={[299.166, 122.365, 143.644]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_35.geometry} material={materials.Chair} position={[277.935, 32.96, 267.991]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_36.geometry} material={materials.Chair} position={[299.166, 122.365, 268.044]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_37.geometry} material={materials.Chair} position={[277.935, 32.96, 383.415]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_38.geometry} material={materials.Chair} position={[299.166, 122.365, 383.467]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_39.geometry} material={materials.Tezgah} position={[156.98, 130.898, 268.244]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_40.geometry} material={materials.Tezgah} position={[-81.508, 130.87, 8.793]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_41.geometry} material={materials.up_Cabinet} position={[105.798, 268.461, -203.185]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_42.geometry} material={materials.Down_Cabinet} position={[-259.179, 81.209, 255.144]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_43.geometry} material={materials.Down_Cabinet} position={[460.604, 81.209, -40.226]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_44.geometry} material={materials.Down_Cabinet} position={[359.747, 81.209, -40.226]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_45.geometry} material={materials.Down_Cabinet} position={[130.397, 81.209, -40.226]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_46.geometry} material={materials.Down_Cabinet} position={[30.128, 81.209, -40.226]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_47.geometry} material={materials.Down_Cabinet} position={[-70.839, 81.209, -40.226]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_48.geometry} material={materials.Down_Cabinet} position={[-259.179, 81.209, 33.5]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_49.geometry} material={materials.Down_Cabinet} position={[-259.179, 81.209, 144.084]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_50.geometry} material={materials.Down_Cabinet} position={[-259.179, 81.209, 144.084]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_51.geometry} material={materials.Down_Cabinet} position={[-259.179, 81.209, 144.084]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

