/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 patio.gltf 
Author: G&L Architectural Graphics Inc (https://sketchfab.com/BERSEKAEL)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/patio-fea3689820264d92930c63203e9d3d49
Title: Patio
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  useGLTF.preload('/3DModels/PatioModels/patio.gltf');
  const { nodes, materials } = useGLTF('/3DModels/PatioModels/patio.gltf');
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.GDLM11_LANDSCAPE__GRASS_3D} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.GDLM12_WOOD__OSB_47} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.GDLM13_INSULATION__FIBERGLAS} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.GDLM14_ROOF__ASPHALT_SHINGLE} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.GDLM16__DECKWHITE_54} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.GDLM2__DECKWOOD2_34} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['GDLM4_COLOR__03_GRAY-LIGHT']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.GDLM5_COLOR__02_WHITEWASH} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.GDLM6_STONEWORK__LEDGERSTON} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.METAL__ZINC} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.counter} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.fireplace} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.grass} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.ground} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.macadam} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.patio_floor} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.stone} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.water} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.house} />
        <lineSegments geometry={nodes.Object_15_1.geometry} material={materials.metal} />
        <mesh geometry={nodes.Object_15_2.geometry} material={materials.metal} />
      </group>
    </group>
  )
}

